AddPrefabPostInit("wathgrithr", function(inst)
	inst:RemoveComponent("eater")
	inst:AddComponent("eater")
end)

AddPrefabPostInit("wurt", function(inst)
    inst:RemoveComponent("eater")
    inst:AddComponent("eater")
    inst:RemoveComponent("foodaffinity")
end)